import{a as u,S as d,i as a}from"./assets/vendor-BGqwtSVv.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f="56856807-1870c2f7a4dca31ed474a7877";function p(s){return u("https://pixabay.com/api/",{params:{key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}}).then(o=>o.data)}const c=document.querySelector(".gallery"),m=new d(".gallery a");function h(){c.innerHTML=""}const l=document.querySelector(".loader");function y(){l.classList.remove("is-hidden")}function g(){l.classList.add("is-hidden")}function L(s){const o=s.map(t=>`<li class="gallery-item">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}">
            </a>
            <p> Likes ${t.likes} </p>
            <p>Views ${t.views}</p> 
            <p> Comments ${t.comments}</p>
            <p> Downloads ${t.downloads}</p>
        </li>`).join("");c.insertAdjacentHTML("beforeend",o),m.refresh()}const b=document.querySelector(".form");b.addEventListener("submit",w);function w(s){s.preventDefault();const o=s.target.elements["search-text"].value.trim();o!==""&&(y(),s.target.reset(),h(),p(o).then(t=>{if(t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(t.hits)}).catch(t=>{a.error({message:"An error occurred.",position:"topRight"})}).finally(()=>{g()}))}
//# sourceMappingURL=index.js.map
